version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - PORTA_TOKEN_ADDRESS=${PORTA_TOKEN_ADDRESS}
      - SOLANA_NETWORK=${SOLANA_NETWORK}
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - porta-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - porta-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  proxy:
    build: .
    command: python -m porta_secura.core.proxy
    ports:
      - "8001:8001"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - redis
    networks:
      - porta-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  porta-network:
    driver: bridge

volumes:
  redis-data: